name: Semgrep

on:
  pull_request:
  workflow_dispatch:
  push: 
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - uses: actions/checkout@v5
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
